# Generated by Django 4.2.1 on 2023-05-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.CharField(choices=[('F', 'Fall'), ('W', 'Winter'), ('Su', 'Summer'), ('Sp', 'Spring')], default='F', max_length=2)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tree')),
            ],
        ),
    ]
