# Generated by Django 4.2.1 on 2023-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='season',
            name='date',
            field=models.DateField(verbose_name='Season date'),
        ),
    ]
