# Generated by Django 4.2.1 on 2023-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pref_alter_season_options_alter_season_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='prefs',
            field=models.ManyToManyField(to='main_app.pref'),
        ),
    ]
